apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ldap-self-service.fullname" . }}
  labels:
{{ include "ldap-self-service.labels" . | indent 4 }}
type: Opaque
stringData:
  config.inc.local.php: |-
    <?php
    {{ range $key, $value := .Values.config }}

    {{- $tp := typeOf $value }}
    {{- if eq $tp "string"}}
    ${{ $key }} = {{ $value | quote }};
    {{- end }}
    {{- if eq $tp "float64"}}
    ${{ $key }} = {{ $value | int64 }};
    {{- end }}
    {{- if eq $tp "int"}}
    ${{ $key }} = {{ $value | int64 }};
    {{- end }}
    {{- if eq $tp "bool"}}
    ${{ $key }} = {{ $value }};
    {{- end }}
    {{- end }}

