{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "matrix-ircd.serviceAccountName" . }}
  labels:
{{ include "matrix-ircd.labels" . | indent 4 }}
{{- end -}}
