apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "turtl.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "turtl.name" . }}
    helm.sh/chart: {{ include "turtl.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "turtl.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "turtl.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml .Values.dnsConfig | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SELF_URL
              value: {{ required "turtl.selfUrl is required if github configuration is specified." .Values.turtl.selfUrl | quote }}
            - name: LOGLEVEL
              value: {{ .Values.turtl.loglevel | quote }}
            - name: DBURL
              valueFrom:
                secretKeyRef:
                  name: {{ template "turtl.fullname" . }}
                  key: dburl
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
          - name: turtl-plugins
            mountPath: /usr/src/app/plugins
          - name: turtl-uploads
            mountPath: /usr/src/app/public/uploads
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: turtl-plugins
        emptyDir: {}
      - name: turtl-uploads
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "turtl.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
