{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "room-assistant.serviceAccountName" . }}
  labels:
{{ include "room-assistant.labels" . | indent 4 }}
{{- end -}}
