apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-appservice-gitter.fullname" . }}
  labels:
{{ include "matrix-appservice-gitter.labels" . | indent 4 }}
type: Opaque
data:
  config.yaml: {{ .Values.config | toYaml | b64enc | quote }}
  gitter-registration.yaml: {{ .Values.registration | toYaml | b64enc | quote }}
