{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "matrix-appservice-gitter.serviceAccountName" . }}
  labels:
{{ include "matrix-appservice-gitter.labels" . | indent 4 }}
{{- end -}}
