apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitter-irc-bridge.fullname" . }}
  labels:
{{ include "gitter-irc-bridge.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6667
      targetPort: irc
      protocol: TCP
      name: irc
    - port: 4567
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "gitter-irc-bridge.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
