{{- if .Values.config }}
{{- if .Values.config.appservice }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mautrix-twitter.fullname" . }}
  labels:
{{ include "mautrix-twitter.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - port: {{ required "need config.appservice.port" .Values.config.appservice.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mautrix-twitter.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
