{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sevendaysdie.serviceAccountName" . }}
  labels:
{{ include "sevendaysdie.labels" . | indent 4 }}
{{- end -}}
