apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-dimension.fullname" . }}
  labels:
{{ include "matrix-dimension.labels" . | indent 4 }}
type: Opaque
data:
  config.yaml: {{ tpl (.Values.config | toYaml) . | b64enc | quote }}
