apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-media-repo.fullname" . }}
  labels:
{{ include "matrix-media-repo.labels" . | indent 4 }}
type: Opaque
data:
  config.yaml: {{ .Values.config | toYaml | b64enc | quote }}
