{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "octoprint.serviceAccountName" . }}
  labels:
{{ include "octoprint.labels" . | indent 4 }}
{{- end -}}
