apiVersion: apps/v1
{{- $podAnnotations := .Values.podAnnotations }}
{{- $secretAnnotation := dict "checksum/secret" (include (print $.Template.BasePath "/secrets.yaml") . | sha256sum) }}
{{- $podAnnotations := merge $podAnnotations $secretAnnotation }}
kind: Deployment
metadata:
  name: {{ include "mastodon-twitter-poster.fullname" . }}-sidekiq
  {{- if .Values.deploymentAnnotations }}
  annotations:
    {{- range $key, $value := .Values.deploymentAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
{{ include "mastodon-twitter-poster.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
{{- if .Values.strategy }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
{{ if eq .Values.strategy.type "Recreate" }}
    rollingUpdate: null
{{- end }}
{{- end }}
  selector:
    matchLabels:
      {{- include "mastodon-twitter-poster.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mastodon-twitter-poster.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- if $podAnnotations }}
      annotations:
        {{- range $key, $value := $podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    spec:
      terminationGracePeriodSeconds: 30 # put your longest Job time here plus security time.
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "mastodon-twitter-poster.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml .Values.dnsConfig | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-sidekiq
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag .}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bundle","exec","sidekiq","-c","5","-q","default"]
          ports:
            - name: healthcheck
              containerPort: 7433
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: healthcheck
            initialDelaySeconds: 80 # app specific. Time your sidekiq takes to start processing.
            timeoutSeconds: 5 # can be much less
          readinessProbe:
            httpGet:
              path: /
              port: healthcheck
            initialDelaySeconds: 80 # app specific
            timeoutSeconds: 5 # can be much less
          lifecycle:
            preStop:
              exec:
                # SIGTERM triggers a quick exit; gracefully terminate instead
                command: ["bundle", "exec", "sidekiqctl", "quiet"]
          envFrom:
            - secretRef:
                name: {{ include "mastodon-twitter-poster.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- if .Values.statsd_exporter.enabled }}
        - name: statsd-exporter
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.statsd_exporter.image.repository }}:{{ tpl .Values.statsd_exporter.image.tag .}}"
          imagePullPolicy: {{ .Values.statsd_exporter.image.pullPolicy }}
          ports:
            - name: statsd-web
              containerPort: 9102
              protocol: TCP
            - name: statsd-udp
              containerPort: 9125
              protocol: TCP
            - name: statsd-tcp
              containerPort: 9125
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /metrics
              port: statsd-web
          readinessProbe:
            httpGet:
              path: /metrics
              port: statsd-web
{{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion }}
          startupProbe:
            httpGet:
              path: /metrics
              port: statsd-web
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
