apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mastodon-twitter-poster.fullname" . }}
  labels:
{{ include "mastodon-twitter-poster.labels" . | indent 4 }}
type: Opaque
data:

  RAILS_ENV: {{ "production" | b64enc | quote }}
  RACK_ENV: {{ "production" | b64enc | quote }}
  RAILS_LOG_TO_STDOUT: {{ "enabled" | b64enc | quote }}
  RAILS_SERVE_STATIC_FILES: {{ "true" | b64enc | quote }}
  RAILS_MAX_THREADS: {{ "5" | b64enc | quote }}

  REDIS_URL: {{ required "Redis url is required" .Values.config.redis_url | b64enc | quote }}

  LIBRATO_EMAIL: {{ default "" .Values.config.librato.email | b64enc | quote }}
  LIBRATO_TOKEN: {{ default "" .Values.config.librato.token | b64enc | quote }}

  TWITTER_CLIENT_ID: {{ required "Twitter client id is required" .Values.config.twitter.client.id | b64enc | quote }}
  TWITTER_CLIENT_SECRET: {{ required "Twitter client secret is required" .Values.config.twitter.client.secret | b64enc | quote }}

  SECRET_KEY_BASE: {{ default "" .Values.config.secret_key_base | b64enc | quote }}
  CROSSPOSTER_APP_NAME: {{ default "" .Values.config.app_name | b64enc | quote }}
  CROSSPOSTER_DOMAIN: {{ default "" .Values.config.domain | b64enc | quote }}
  {{- if .Values.config.repo }}
  CROSSPOSTER_REPO: {{ .Values.config.repo | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.stats }}
  CROSSPOSTER_STATS: {{ .Values.config.stats | b64enc | quote }}
  {{- end }}
{{- if .Values.statsd_exporter.enabled }}
  STATSD_ENABLED: {{ "true" | b64enc | quote }}
  STATSD_HOST: {{ "127.0.0.1" | b64enc | quote }}
  STATSD_PORT: {{ "9125" | b64enc | quote }}
{{- else }}
  STATSD_ENABLED: {{ default "" .Values.config.statsd.enabled | b64enc | quote }}
  STATSD_HOST: {{ default "" .Values.config.statsd.host | b64enc | quote }}
  STATSD_PORT: {{ default "" .Values.config.statsd.port | toString | b64enc | quote }}
{{- end }}

  {{- if .Values.config.announcement_url }}
  CROSSPOSTER_FEDI_ACCOUNT_ADDRESS: {{ default "" .Values.config.announcement_url | toString | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.admin.twitter }}
  CROSSPOSTER_ADMIN_TWITTER: {{ default "" .Values.config.admin.twitter | toString | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.admin.fedi.address }}
  CROSSPOSTER_ADMIN_FEDI_ADDRESS: {{ default "" .Values.config.admin.fedi.address | toString | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.admin.fedi.at }}
  CROSSPOSTER_ADMIN_FEDI_AT: {{ default "" .Values.config.admin.fedi.at | toString | b64enc | quote }}
  {{- end }}

  {{- if and (.Values.config.federation_domains.allowed) (gt (len .Values.config.federation_domains.allowed) 0) }}
  ALLOWED_DOMAINS: {{ include "mastodon-twitter-poster.joinListWithComma" .Values.config.federation_domains.allowed | b64enc | quote }}
  {{- end }}
  {{- if and (.Values.config.federation_domains.blocked) (gt (len .Values.config.federation_domains.blocked) 0) }}
  BLOCKED_DOMAINS: {{ include "mastodon-twitter-poster.joinListWithComma" .Values.config.federation_domains.blocked | b64enc | quote }}
  {{- end }}

  {{- if .Values.alternative_twitter_domain }}
  USE_ALTERNATIVE_TWITTER_DOMAIN: {{ "true" | b64enc | quote }}
  ALTERNATIVE_TWITTER_DOMAIN: {{ .Values.config.alternative_twitter_domain | b64enc | quote }}
  {{- end }}


  {{- if .Values.config.database.uri }}
  DATABASE_URL: {{ .Values.config.database.uri | b64enc | quote }}
  {{- else }}
  DB_HOST: {{ required "db host is required" .Values.config.database.host | b64enc | quote }}
  DB_NAME: {{ required "db name is required" .Values.config.database.name | b64enc | quote }}
  DB_USER: {{ required "db user is required" .Values.config.database.user | b64enc | quote }}
  DB_PASS: {{ required "db pass is required" .Values.config.database.pass | b64enc | quote }}
  {{- end }}
