apiVersion: v1
kind: Service
metadata:
  name: {{ include "mastodon-twitter-poster.fullname" . }}
  labels:
{{ include "mastodon-twitter-poster.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mastodon-twitter-poster.selectorLabels" . | nindent 4 }}
