apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pihole.fullname" . }}
  labels:
    app: {{ template "pihole.name" . }}
    chart: {{ template "pihole.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if .Values.pihole.customConfig }}
  05-custom.conf: {{ toYaml .Values.pihole.customConfig | indent 2 }}
  {{- end }}
  {{- if and (.Values.pihole.whitelist) (gt (len .Values.pihole.whitelist) 0) }}
  whitelist.txt:
    {{- range .Values.pihole.whitelist }}
    {{ . }}
    {{- end }}
  {{- end }}
