
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}
  annotations:
    kubernetes.io/allow-mixed-protocol: "true"
    metallb.universe.tf/allow-shared-ip: {{ include "pihole.fullname" . }}
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
    helm.sh/chart: {{ include "pihole.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{ if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{ end }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.https.port }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.dns.port }}
      targetPort: dns1
      protocol: TCP
      name: dns1
      {{ if not (eq .Values.service.type "LoadBalancer") }}
    - port: {{ .Values.service.dns.port }}
      targetPort: dns2
      protocol: UDP
      name: dns2
      {{ end }}
  selector:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ if eq .Values.service.type "LoadBalancer" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}-udp
  annotations:
    kubernetes.io/allow-mixed-protocol: "true"
    metallb.universe.tf/allow-shared-ip: {{ include "pihole.fullname" . }}
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
    helm.sh/chart: {{ include "pihole.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{ if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{ end }}
  ports:
    - port: {{ .Values.service.dns.port }}
      targetPort: dns2
      protocol: UDP
      name: dns2
  selector:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}
