{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mjpg-streamer.serviceAccountName" . }}
  labels:
{{ include "mjpg-streamer.labels" . | indent 4 }}
{{- end -}}
