apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "discord-streamers.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "discord-streamers.name" . }}
    helm.sh/chart: {{ include "discord-streamers.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  .discord-streamers.yaml: |
{{- if .Values.config }}
{{ toYaml .Values.config | indent 6 }}
{{- end }}
