apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns.fullname" . }}
  labels:
{{ include "powerdns.labels" . | indent 4 }}
type: Opaque
data:
  postgres_host: "{{ .Values.powerdns.postgres.host | b64enc }}"
  postgres_port: "{{ .Values.powerdns.postgres.port | toString | b64enc }}"
  postgres_username: "{{ .Values.powerdns.postgres.username | b64enc }}"
  postgres_password: "{{ .Values.powerdns.postgres.password | toString | b64enc }}"
  postgres_database: "{{ .Values.powerdns.postgres.database | b64enc }}"
