{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "irslackd.serviceAccountName" . }}
  labels:
{{ include "irslackd.labels" . | indent 4 }}
{{- end -}}
