apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi-poller.fullname" . }}
  labels:
{{ include "unifi-poller.labels" . | indent 4 }}
{{- if or (not .Values.config.prometheus.disable) (.Values.service.annotations) }}
  annotations:
    {{- if not .Values.config.prometheus.disable }}
    prometheus.io/path: /metrics
    prometheus.io/port: "9130"
    prometheus.io/scrape: "true"
    {{- end }}
    {{- if .Values.service.annotations }}
    {{ toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "unifi-poller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
