{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "unifi-poller.serviceAccountName" . }}
  labels:
{{ include "unifi-poller.labels" . | indent 4 }}
{{- end -}}
