apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thunderdome-planning-poker.fullname" . }}
  labels:
{{ include "thunderdome-planning-poker.labels" . | indent 4 }}
data:
  PORT: {{ "3000" | b64enc | quote }}
  APP_DOMAIN: {{ .Values.config.app_domain | toString | b64enc | quote }}
  DB_HOST: {{ .Values.config.database.host | toString | b64enc | quote }}
  DB_PORT: {{ .Values.config.database.port | toString | b64enc | quote }}
  DB_USER: {{ .Values.config.database.user | toString | b64enc | quote }}
  DB_PASS: {{ .Values.config.database.password | toString | b64enc | quote }}
  DB_NAME: {{ .Values.config.database.name | toString | b64enc | quote }}
  SMTP_HOST: {{ .Values.config.smtp.host | toString | b64enc | quote }}
  SMTP_PORT: {{ .Values.config.smtp.port | toString | b64enc | quote }}
{{- if .Values.config.smtp.secure}}
  SMTP_SECURE: 1
{{- end }}
  SMTP_IDENTITY: {{ .Values.config.smtp.identity | toString | b64enc | quote }}
  SMTP_SENDER: {{ .Values.config.smtp.sender | toString | b64enc | quote }}
  SMTP_NAME: {{ .Values.config.smtp.name | toString | b64enc | quote }}
