{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "thunderdome-planning-poker.serviceAccountName" . }}
  labels:
{{ include "thunderdome-planning-poker.labels" . | indent 4 }}
{{- end -}}
