apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hubot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hubot.name" . }}
    helm.sh/chart: {{ include "hubot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hubot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hubot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml .Values.dnsConfig | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HUBOT_NAME
              value: {{ .Values.name | quote }}
            - name: HUBOT_ADAPTER
              value: {{ .Values.adapter.type | quote }}
            {{ range $key, $value := .Values.env -}}
            - name: {{ $key | upper }}
              value: {{ $value | quote }}
            {{ end }}
            {{ range $key, $value := .Values.brain.env -}}
            - name: {{ $key | upper }}
              value: {{ $value | quote }}
            {{ end }}
            {{ range $key, $value := .Values.adapter.env -}}
            - name: {{ $key | upper }}
              value: {{ $value | quote }}
            {{ end }}
          #command: ["/bin/sh", "-c"]
          #args: ["sleep 1d"]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
