apiVersion: v1
kind: Secret
metadata:
  name: {{ include "psitransfer.fullname" . }}
  labels:
{{ include "psitransfer.labels" . | indent 4 }}
type: Opaque
data:
  PSITRANSFER_ADMIN_PASS: {{ required "Admin pass config is required" .Values.config.adminPass | b64enc | quote }}
  PSITRANSFER_UPLOAD_PASS: {{ .Values.config.uploadPass | default "" | b64enc | quote }}
