apiVersion: v1
kind: Service
metadata:
  name: {{ include "psitransfer.fullname" . }}
  labels:
{{ include "psitransfer.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "psitransfer.selectorLabels" . | nindent 4 }}
